apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: go_client
  labels:
    app: go_client
spec:
  replicas: 1
  template:
    metadata:
      name: go_client
      labels:
        app: go_client
    spec:
      serviceAccountName: prometheus-k8s
      containers:
      - name: prometheus
        image: registry.cn-qingdao.aliyuncs.com/ruipages/go_client
        command: ["./random "]
        args: ["-listen-address=:8080"]
        ports:
          - containerPort: 8080

---

kind: Service
apiVersion: v1
metadata:
  name: go_client-svc
spec:
  selector:
    run: go_client
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
