apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: go-client
  labels:
    app: go-client
spec:
  replicas: 1
  template:
    metadata:
      name: go-client
      labels:
        app: go-client
    spec:
      containers:
      - name: goclient
        image: registry.cn-qingdao.aliyuncs.com/ruipages/go_client
        command: ["./random "]
        args: ["-listen-address=:8080"]
        ports:
          - containerPort: 8080

---

kind: Service
apiVersion: v1
metadata:
  name: go-client-svc
spec:
  selector:
    run: go-client
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
